Repository UserOfficeProject/user-office-core, pull requests merged in 2024-02, with the labels that each got.

#495 Update husky hooks following v9 update
  .husky/pre-commit
  package.json
Labels: review: please

#491 981 display summary of scored proposals
  apps/e2e/cypress/e2e/FAPs.cy.ts
  apps/frontend/src/components/fap/Proposals/FapProposalsAndAssignmentsTable.tsx
Labels: review: please

#498 chore: Update cache action to v4
  .github/workflows/test-build.yml
Labels: review: please

#486 Improve proposal search by waiting for user to finish typing search term
  apps/frontend/src/components/proposal/ProposalTableInstrumentScientist.tsx
  apps/frontend/src/components/proposal/ProposalTableOfficer.tsx
Labels: review: please

#478 Fix: Stop assigning STFC users to FAP without roles
  apps/backend/src/config/dependencyConfigSTFC.ts
  apps/backend/src/datasources/stfc/StfcFapDataSource.ts
  apps/backend/src/datasources/stfc/StfcUserDataSource.ts
  apps/backend/src/mutations/FapMutations.ts
  apps/e2e/cypress/e2e/settings.cy.ts
Labels: review: please

#496 Add a view to simplify proposal answer access in SQL queries
  apps/backend/db_patches/0147_AddProposalAnswerView.sql
Labels: review: please

#502 Release 2024 02 07
  .github/workflows/test-build.yml
  .husky/pre-commit
  apps/backend/db_patches/0147_AddProposalAnswerView.sql
  apps/backend/package-lock.json
  apps/backend/package.json
  apps/backend/src/auth/OAuthAuthorization.ts
  apps/backend/src/buildContext.ts
  apps/backend/src/config/dependencyConfigSTFC.ts
  apps/backend/src/context/index.ts
  apps/backend/src/datasources/UserDataSource.ts
  apps/backend/src/datasources/mockups/UserDataSource.ts
  apps/backend/src/datasources/postgres/CallDataSource.test.ts
  apps/backend/src/datasources/postgres/CallDataSource.ts
  apps/backend/src/datasources/postgres/TemplateDataSource.ts
  apps/backend/src/datasources/postgres/UserDataSource.ts
  apps/backend/src/datasources/stfc/StfcFapDataSource.ts
  apps/backend/src/datasources/stfc/StfcProposalDataSource.ts
  apps/backend/src/datasources/stfc/StfcUserDataSource.ts
  apps/backend/src/loaders/UsersLoader.ts
  apps/backend/src/mutations/FapMutations.ts
  apps/backend/src/mutations/ProposalMutations.ts
  apps/backend/src/queries/UserQueries.ts
  apps/backend/src/resolvers/mutations/ImportProposalMutation.ts
  apps/backend/src/resolvers/mutations/UpdateProposalMutation.ts
  apps/backend/src/resolvers/types/BasicUserDetails.ts
  apps/backend/src/resolvers/types/ProposalView.ts
  apps/e2e/cypress/e2e/FAPs.cy.ts
  apps/e2e/cypress/e2e/instruments.cy.ts
  apps/e2e/cypress/e2e/proposals.cy.ts
  apps/e2e/cypress/e2e/settings.cy.ts
  apps/e2e/cypress/e2e/userAdministration.cy.ts
  apps/frontend/.dockerignore
  apps/frontend/Dockerfile
  apps/frontend/default.conf
  apps/frontend/package-lock.json
  apps/frontend/package.json
  apps/frontend/src/components/fap/Proposals/FapProposalsAndAssignmentsTable.tsx
  apps/frontend/src/components/instrument/AssignedScientistsTable.tsx
  apps/frontend/src/components/instrument/CreateUpdateInstrument.tsx
  apps/frontend/src/components/instrument/InstrumentTable.tsx
  apps/frontend/src/components/proposal/ProposalParticipant.tsx
  apps/frontend/src/components/proposal/ProposalTable.tsx
  apps/frontend/src/components/proposal/ProposalTableInstrumentScientist.tsx
  apps/frontend/src/components/proposal/ProposalTableOfficer.tsx
  apps/frontend/src/components/review/ProposalGrade.tsx
  apps/frontend/src/components/review/ProposalTableReviewer.tsx
  apps/frontend/src/components/review/ProposalTechnicalReview.tsx
  apps/frontend/src/components/review/ReviewStatusFilter.tsx
  apps/frontend/src/graphql/proposal/getProposal.graphql
  apps/frontend/src/hooks/user/useUserData.ts
  apps/frontend/src/hooks/user/useUsersDataByFilter.ts
  apps/frontend/src/utils/user.ts
  package-lock.json
  package.json
Labels: review: please

#501 Remove outdated database dump
  apps/backend/db.sql
Labels: review: please

#507 This removes tls by default when smtp login not set
  apps/backend/package-lock.json
  apps/backend/package.json
  apps/backend/src/eventHandlers/MailService/SMTPMailService.ts
Labels: review: please

#504 Chore: Fix codeql analysis warning
  .github/workflows/codeql-analysis.yml
Labels: review: please

#510 Merge back release 5.31.1
  apps/backend/package-lock.json
  apps/backend/package.json
  apps/backend/src/eventHandlers/MailService/SMTPMailService.ts
Labels: review: please

#503 feat: pass iss parameter to openid auth server on callback
  apps/backend/package-lock.json
  apps/backend/package.json
  apps/backend/src/auth/OAuthAuthorization.ts
  apps/backend/src/auth/UserAuthorization.ts
  apps/backend/src/mutations/UserMutations.spec.ts
  apps/backend/src/mutations/UserMutations.ts
  apps/backend/src/resolvers/mutations/CheckExternalTokenMutation.ts
  apps/e2e/cypress/e2e/genericTemplates.cy.ts
  apps/e2e/cypress/support/filterTests.ts
  apps/e2e/cypress/support/user.ts
  apps/frontend/src/components/user/ExternalAuth.tsx
  apps/frontend/src/graphql/user/externalTokenLogin.graphql
Labels: review: please

#468 Renaming organization to institution
  apps/backend/db_patches/0146_RenameOrganisationColumn.sql
  apps/backend/db_patches/db_seeds/0002_InstrumentScientiests.sql
  apps/backend/package-lock.json
  apps/backend/package.json
  apps/backend/src/auth/OAuthAuthorization.ts
  apps/backend/src/datasources/UserDataSource.ts
  apps/backend/src/datasources/mockups/UserDataSource.ts
  apps/backend/src/datasources/postgres/AdminDataSource.ts
  apps/backend/src/datasources/postgres/FapDataSource.ts
  apps/backend/src/datasources/postgres/InstrumentDataSource.ts
  apps/backend/src/datasources/postgres/UserDataSource.ts
  apps/backend/src/datasources/postgres/records.ts
  apps/backend/src/datasources/stfc/StfcInstrumentDataSource.ts
  apps/backend/src/datasources/stfc/StfcUserDataSource.ts
  apps/backend/src/eventHandlers/email/essEmailHandler.ts
  apps/backend/src/models/User.ts
  apps/backend/src/mutations/UserMutations.ts
  apps/backend/src/queries/UserQueries.ts
  apps/backend/src/resolvers/mutations/UpdateUserMutation.ts
  apps/backend/src/resolvers/types/BasicUserDetails.ts
  apps/backend/src/resolvers/types/User.ts
  apps/backend/src/resolvers/types/UserJWT.ts
  apps/e2e/cypress/e2e/FAPs.cy.ts
  apps/e2e/cypress/e2e/eventLogs.cy.ts
  apps/e2e/cypress/e2e/personalInformation.cy.ts
  apps/e2e/cypress/e2e/userAdministration.cy.ts
  apps/frontend/package-lock.json
  apps/frontend/package.json
  apps/frontend/src/components/AppToolbar/AppToolbar.tsx
  apps/frontend/src/components/fap/Members/FapMembers.tsx
  apps/frontend/src/components/fap/Proposals/AssignFapMemberToProposalModal.tsx
  apps/frontend/src/components/fap/Proposals/FapProposalsAndAssignmentsTable.tsx
  apps/frontend/src/components/instrument/AssignedScientistsTable.tsx
  apps/frontend/src/components/instrument/InstrumentTable.tsx
  apps/frontend/src/components/proposal/ProposalParticipant.tsx
  apps/frontend/src/components/template/PdfTemplateDefaultData.tsx
  apps/frontend/src/components/template/documentation.tsx
  apps/frontend/src/components/user/InviteUserForm.tsx
  apps/frontend/src/components/user/PeopleTable.tsx
  apps/frontend/src/components/user/ProposalsPeopleTable.tsx
  apps/frontend/src/components/user/UpdateUserInformation.tsx
  apps/frontend/src/components/visit/CreateVisitRegistration.tsx
  apps/frontend/src/context/UserContextProvider.tsx
  apps/frontend/src/graphql/fap/getFapProposals.graphql
  apps/frontend/src/graphql/proposal/getInstrumentScientistProposals.graphql
  apps/frontend/src/graphql/proposal/getProposalsCore.graphql
  apps/frontend/src/graphql/review/userWithReviews.graphql
  apps/frontend/src/graphql/user/fragment.basicUserInformation.graphql
  apps/frontend/src/graphql/user/getUser.graphql
  apps/frontend/src/graphql/user/getUserMe.graphql
  apps/frontend/src/graphql/user/updateUser.graphql
  apps/frontend/src/hooks/user/useUserData.ts
  apps/frontend/src/utils/user.ts
Labels: review: please, breaking:change

#519 feat: add institution to the User object as it exists in BasicUserInfo
  apps/backend/src/datasources/mockups/UserDataSource.ts
  apps/backend/src/datasources/postgres/UserDataSource.ts
  apps/backend/src/datasources/postgres/records.ts
  apps/backend/src/datasources/stfc/StfcUserDataSource.ts
  apps/backend/src/models/User.ts
Labels: review: please

#521 Set connection pool recommended min
  apps/backend/src/datasources/postgres/database.ts
Labels: review: please

#513 View Reviewer's Assigned Proposals In Current Call
  apps/backend/src/datasources/FapDataSource.ts
  apps/backend/src/datasources/mockups/FapDataSource.ts
  apps/backend/src/datasources/postgres/CallDataSource.ts
  apps/backend/src/datasources/postgres/FapDataSource.ts
  apps/backend/src/datasources/stfc/StfcFapDataSource.ts
  apps/backend/src/resolvers/queries/FapQuery.ts
  apps/backend/src/resolvers/types/FapReviewers.ts
  apps/e2e/cypress/e2e/FAPs.cy.ts
  apps/e2e/cypress/e2e/proposals.cy.ts
  apps/e2e/cypress/support/utils.ts
  apps/frontend/src/components/fap/Members/FapMembers.tsx
  apps/frontend/src/graphql/fap/getFapReviewers.graphql
Labels: review: please

#527 feat: custom emails to FAP chair and secretary
  apps/backend/src/resolvers/types/ProposalStatusActionConfig.ts
  apps/backend/src/statusActionEngine/emailActionHandler.ts
  apps/backend/src/statusActionEngine/statusActionUtils.ts
Labels: review: please

#524 Add option to omit images from proposal pdf
  apps/backend/src/models/ProposalModelFunctions.ts
  apps/backend/src/models/questionTypes/FileUpload.ts
  apps/backend/src/resolvers/types/FieldConfig.ts
  apps/e2e/cypress/fixtures/template_export.json
  apps/frontend/src/components/common/FileUploadComponent.tsx
  apps/frontend/src/components/questionary/questionaryComponents/FileUpload/QuestionFileUploadForm.tsx
  apps/frontend/src/components/questionary/questionaryComponents/FileUpload/QuestionTemplateRelationFileUploadForm.tsx
  apps/frontend/src/components/questionary/questionaryComponents/FileUpload/QuestionaryComponentFileUpload.tsx
  apps/frontend/src/components/review/ProposalTechnicalReview.tsx
  apps/frontend/src/graphql/template/fragment.fieldConfig.graphql
Labels: review: please

#530 fix: recurring users query when expanding instrument users and page refresh when pressing enter after surname search in instrument creation
  apps/e2e/cypress/e2e/instruments.cy.ts
  apps/frontend/src/components/instrument/AssignedScientistsTable.tsx
  apps/frontend/src/components/instrument/CreateUpdateInstrument.tsx
  apps/frontend/src/graphql/instrument/instrument.fragment.graphql
  apps/frontend/src/hooks/user/useUsersDataByFilter.ts
Labels: bug, review: please

#532 Proposal release 28-02-2024
  apps/e2e/cypress/e2e/instruments.cy.ts
  apps/frontend/src/components/instrument/AssignedScientistsTable.tsx
  apps/frontend/src/components/instrument/CreateUpdateInstrument.tsx
  apps/frontend/src/graphql/instrument/instrument.fragment.graphql
  apps/frontend/src/hooks/user/useUsersDataByFilter.ts
Labels: review: please
